version: "3.8"

services:
  frontend-prod:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: bemat-frontend-prod
    restart: unless-stopped
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - ../.env.prod
        #environment:
        #- NODE_ENV=production
    labels:
      - "com.bemat.description=BEMAT Frontend Production"
      - "com.bemat.service=frontend"
      - "com.bemat.environment=production"
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`energymanagement.epu.ntua.gr`) &&  PathPrefix(`/`)"
      - "traefik.http.routers.frontend.entrypoints=https"
      - "traefik.http.routers.frontend.tls=true"
      - "traefik.http.routers.frontend.tls.certresolver=myresolver"
      - "traefik.http.services.frontend.loadbalancer.server.port=80"
      # Optional: HTTP to HTTPS redirect
      #- "traefik.http.routers.frontend-http.rule=Host(`energymanagement.epu.ntua.gr`)"
      #- "traefik.http.routers.frontend-http.entrypoints=http"
      #- "traefik.http.routers.frontend-http.middlewares=redirect-to-https"
      #- "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
    networks:
      - proxy_net

networks:
  proxy_net:
    external: true
