version: '3.8'

services:
  frontend-prod:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: bemat-frontend-prod
    ports:
      - "3000:80"
    restart: unless-stopped
    networks:
      - bemat-network
    env_file:
      - ../.env.prod
    environment:
      - NODE_ENV=production
    labels:
      - "com.bemat.description=BEMAT Frontend Production"
      - "com.bemat.service=frontend"
      - "com.bemat.environment=production"

networks:
  bemat-network:
    driver: bridge
